apiVersion: apps/v1

kind: Deployment

metadata:

  name: cit270jacobservice
  
spec:

    replicas: 1

    selector:

      matchLabels:
        
        app: cit270jacobservice
    template:
      metadata:
        name: cit270jacobservice
        labels:
          app: cit270jacobservice
      spec:
        containers:
        - name: cit270jacobservice
          image: gcr.io/kubernetesproject2/cit270-fall2022

         # volumeMounts:
          #- name: ssl
              
          #  mountPath: "/etc/letsencrypt/live/jacobcausey.cit270.com"
              
          command: ["npm"]
          args: ["run","start"]

          resources:
            requests:
              cpu: 0.125
              memory: 500Mi
            limits:
              cpu: 0.125

              memory: 600Mi
          imagePullPolicy: Always
        #volumes:
          #- name: ssl
           # secret:
            #  secretName: jacobcerts
#---
# apiVersion: v1

# kind: Service

# metadata:

#   name: cit270jacobservice-loadbalancer
# spec:

#   selector:
#     app: cit270jacobservice
#   type: LoadBalancer
#   ports:
#   - port: 443
#     targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-jacobcausey-nodeport
spec:
  selector:
    app: cit270jacobservice
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-jacobcausey-certificate
spec:
  domains:
    - jacobcausey.cit270.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-jacobcausey-ingress
  labels:
    name: myingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-jacobcausey-nodeport
            port: 
              number: 80
