apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stedi-jacob
spec:
  selector:
    matchLabels:
      app: redis-stedi-jacob
  serviceName: redis-stedi-jacob
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-stedi-jacob
    spec:
      containers:
        - name: redis-stedi-jacob
          image: redis:7.0.5-apline
          imagePullPolicy: Always
          args: ["--requirepass", "$(REDIS_PASS)", "--appendonly", "yes", "--save","900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6397
